# Generated by Django 5.2.11 on 2026-02-25 04:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GHN', 'Giao hàng nhanh'), ('GHHT', 'Giao hàng hỏa tốc'), ('GHTK', 'Giao hàng tiết kiệm')], default='GHN', max_length=100)),
                ('code', models.CharField(help_text='Dùng mã GHN, GHHT, GHTK', max_length=20, unique=True)),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='Giá ship mặc định cho khu vực nội thành', max_digits=12)),
                ('estimate_delivery_days', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='is_freeship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='product_voucher',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_discounted_orders', to='promotions.voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_voucher',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type': 'SHIPPING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_discounted_orders', to='promotions.voucher'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('CASH', 'Tiền mặt khi nhận hàng')], db_index=True, default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.shippingmethod'),
        ),
    ]
