# Generated by Django 5.2.10 on 2026-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_note',
            field=models.TextField(blank=True, default='', help_text='Lời nhắn tặng quà'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
