import fs from 'fs';

const INPUT = [
    {
        name: "Thành phố Đà Nẵng",
        wards: [
            "Phường Hải Châu 1", "Phường Hải Châu 2", "Phường Thạch Thang", 
            "Phường Thuận Phước", "Phường Hòa Thuận Đông", "Phường Hòa Thuận Tây", 
            "Phường Bình Thuận", "Phường Hòa Cường Bắc", "Phường Hòa Cường Nam",
            "Phường Vĩnh Trung", "Phường Thạc Gián", "Phường Thanh Khê Đông", "Phường An Khê",
            "Phường An Hải Bắc", "Phường An Hải Đông", "Phường Phước Mỹ", "Phường Thọ Quang",
            "Phường Mỹ An", "Phường Khuê Mỹ", "Phường Hòa Quý", "Phường Hòa Hải",
            "Phường Khuê Trung", "Phường Hòa Xuân", "Phường Hòa An",
            "Phường Hòa Minh", "Phường Hòa Khánh Bắc", "Phường Hòa Hiệp Nam",
            "Xã Hòa Châu", "Xã Hòa Tiến", "Xã Hòa Liên", "Xã Hòa Nhơn", "Xã Hòa Phong"
        ]
    },
    {
        name: "Thành phố Hà Nội",
        wards: [
            "Phường Ba Đình", "Phường Hoàn Kiếm",
            "Phường Đống Đa", "Phường Hai Bà Trưng",
            "Phường Cầu Giấy", "Phường Tây Hồ",
            "Phường Thanh Xuân", "Phường Hoàng Mai",
            "Phường Long Biên", "Phường Nam Từ Liêm"
        ]
    },
    {
        name: "Thành phố Hồ Chí Minh",
        wards: [
            "Phường Bến Nghé", "Phường Bến Thành",
            "Phường Nguyễn Thái Bình", "Phường Phạm Ngũ Lão",
            "Phường Cô Giang", "Phường Thảo Điền",
            "Phường An Phú", "Phường Bình Thạnh",
            "Phường Tân Định", "Phường Đa Kao"
        ]
    }
];

// Delay tránh spam Nominatim (rate limit: 1 req/giây)
const delay = ms => new Promise(res => setTimeout(res, ms));

async function geocode(query) {
    const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query + ', Việt Nam')}&format=json&limit=1`;
    const res = await fetch(url, {
        headers: { 'User-Agent': 'ShuttleXEcommerce/1.0' } 
    });
    const data = await res.json();
    if (data.length === 0) return null;
    return {
        lat: parseFloat(parseFloat(data[0].lat).toFixed(6)),
        lng: parseFloat(parseFloat(data[0].lon).toFixed(6))
    };
}

async function generate() {
    const result = [];

    for (const province of INPUT) {
        console.log(`\n[ MAP ] - Đang xử lý: ${province.name}`);

        await delay(1100);
        const provCoords = await geocode(province.name);
        if (!provCoords) {
            console.warn(`[ MAP ] - Không tìm được tọa độ cho ${province.name}`);
            continue;
        }
        console.log(`[ MAP ] - Tỉnh: ${provCoords.lat}, ${provCoords.lng}`);

        const wards = [];
        for (const wardName of province.wards) {
            await delay(1100);
            const wardCoords = await geocode(`${wardName}, ${province.name}`);

            if (wardCoords) {
                console.log(`[ MAP ] - ${wardName}: ${wardCoords.lat}, ${wardCoords.lng}`);
                wards.push({ name: wardName, ...wardCoords });
            } else {
                console.warn(`[ MAP ] - Fallback tọa độ tỉnh cho: ${wardName}`);
                wards.push({ name: wardName, ...provCoords });
            }
        }

        result.push({
            name: province.name,
            ...provCoords,
            wards
        });
    }

    const jsContent = `// Auto-generated by scripts/generateProvinces.js
// Dữ liệu tọa độ từ OpenStreetMap Nominatim
// Tái tạo: node scripts/generateProvinces.js

const PROVINCES = ${JSON.stringify(result, null, 2)};

export default PROVINCES;
`;

    if (!fs.existsSync('src/data')){
        fs.mkdirSync('src/data', { recursive: true });
    }

    fs.writeFileSync('src/data/provinces.js', jsContent, 'utf-8');
    console.log('\n[ MAP ] - Hoàn tất! File lưu tại: src/data/provinces.js');
    console.log(`   ${result.length} tỉnh, ${result.reduce((a, p) => a + p.wards.length, 0)} phường/xã`);
}

generate().catch(console.error);