# Generated by Django 6.0.2 on 2026-02-23 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, help_text='Thời hạn sale; nếu null thì sale không giới hạn theo thời gian.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá khuyến mãi; nếu null hoặc hết hạn sẽ không dùng.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá gốc của loại sản phẩm. Nếu để trống sẽ fallback về base_price của Product.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
