# Generated by Django 5.2.10 on 2026-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_sale_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity used when product has no variants. Ignored if variants exist.'),
        ),
    ]
