# Generated by Django 5.2.10 on 2026-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags for search, separated by commas or spaces', max_length=512, null=True),
        ),
    ]
