# Generated by Django 5.2.10 on 2026-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_flashsale_flashsaleitem_flashsale_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='new_customer_only',
            field=models.BooleanField(default=False, help_text='Chỉ áp dụng cho khách hàng chưa có đơn trước đó.'),
        ),
    ]
