# Generated by Django 5.2.10 on 2026-03-28 15:24

import django.db.models.deletion
from django.db import migrations, models


def create_type_options(apps, schema_editor):
    VoucherTypeOption = apps.get_model('promotions', 'VoucherTypeOption')
    DiscountTypeOption = apps.get_model('promotions', 'DiscountTypeOption')
    
    # Create voucher types
    VoucherTypeOption.objects.get_or_create(
        code="PRODUCT",
        defaults={"label": "Giảm giá sản phẩm", "description": ""}
    )
    VoucherTypeOption.objects.get_or_create(
        code="SHIPPING",
        defaults={"label": "Giảm phí vận chuyển", "description": ""}
    )
    
    # Create discount types
    DiscountTypeOption.objects.get_or_create(
        code="PERCENTAGE",
        defaults={"label": "Phần trăm (%)", "description": ""}
    )
    DiscountTypeOption.objects.get_or_create(
        code="FIXED",
        defaults={"label": "Số tiền cố định (đ)", "description": ""}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_voucher_new_customer_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loại giảm giá',
                'verbose_name_plural': 'Loại giảm giá',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loại mã giảm giá',
                'verbose_name_plural': 'Loại mã giảm giá',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_type_options),
        # Add temp fields to store new FK values
        migrations.AddField(
            model_name='voucher',
            name='voucher_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_temp', to='promotions.vouchertypeoption'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_temp2', to='promotions.discounttypeoption'),
        ),
        # Migrate data from old CharField to new FK fields
        migrations.RunSQL(
            sql="""
                UPDATE promotions_voucher v
                SET discount_type_new_id = (SELECT id FROM promotions_discounttypeoption WHERE code = v.discount_type)
                WHERE v.discount_type IS NOT NULL;
                
                UPDATE promotions_voucher v
                SET voucher_type_new_id = (SELECT id FROM promotions_vouchertypeoption WHERE code = v.voucher_type)
                WHERE v.voucher_type IS NOT NULL;
            """,
            reverse_sql="",
        ),
        # Remove old CharField fields
        migrations.RemoveField(
            model_name='voucher',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_type',
        ),
        # Rename new FK fields to original names
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_type_new',
            new_name='voucher_type',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='discount_type_new',
            new_name='discount_type',
        ),
        # Update related_name back to original
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='promotions.vouchertypeoption'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='promotions.discounttypeoption'),
        ),
    ]
