# Generated by Django 5.2.10 on 2026-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_discounttypeoption_vouchertypeoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttypeoption',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vouchertypeoption',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
