# Generated by Django 5.2.10 on 2026-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_discounttypeoption_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='limit_usage',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
