# Generated by Django 5.2.10 on 2026-03-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_normalize_zero_limit_usage'),
        ('promotions', '000X_add_voucher_description'),
    ]

    operations = [
    ]
