# Generated by Django 5.2.10 on 2026-05-06 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_base_stock'),
        ('promotions', '0008_merge_20260329_0440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flashsaleitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Nếu chọn variant, Flash Sale chỉ áp dụng cho biến thể này. Nếu để trống, áp dụng cho toàn bộ sản phẩm.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together={('flash_sale', 'product', 'variant')},
        ),
    ]
