# Generated by Django 5.2.10 on 2026-05-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_sku'),
        ('promotions', '0009_alter_flashsaleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsaleitem',
            name='flash_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.flashsale'),
        ),
        migrations.AlterField(
            model_name='flashsaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='flashsaleitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Nếu chọn variant, Flash Sale chỉ áp dụng cho biến thể này. Nếu để trống, áp dụng cho toàn bộ sản phẩm.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='catalog.productvariant'),
        ),
    ]
