# Generated by Django 5.2.10 on 2026-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_contact', models.CharField(default='0123456789', max_length=20)),
                ('zalo_link', models.CharField(default='https://zalo.me/0123456789', help_text='Link Zalo để hỗ trợ khách hàng', max_length=255, verbose_name='Link Zalo')),
                ('facebook_link', models.CharField(default='https://m.me/shuttlex', max_length=255, verbose_name='Link Messenger')),
                ('email_contact', models.EmailField(default='contact@shuttlex.com', max_length=254, verbose_name='Email liên hệ')),
                ('address_contact', models.CharField(default='642 đường Tôn Đức Thắng, Phường Hòa Khánh, Thành phố Đà Nẵng', max_length=255, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
            },
        ),
    ]
