# Generated by Django 5.2.10 on 2026-05-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='comment',
            new_name='content',
        ),
    ]
