function BrandForm({ values, onChange, onSubmit, onCancel }) {
  const generateSlug = (text) => {
    return text
      .toString()
      .toLowerCase()
      .normalize('NFD') //tách dấu
      .replace(/[\u0300-\u036f]/g, '') //xóa dấu
      .replace(/[^\w\s-]/g, '') // Xóa ký tự đặc biệt
      .trim()
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
  }

  const handleChange = (event) => {
    const { name, value, type, checked } = event.target
    
    if (name === "name") {
      const newSlug = generateSlug(value)
      const autoGeneratedSlugFromPrevName = generateSlug(values.name || "")
      const shouldUpdateSlug = !values.slug || values.slug === autoGeneratedSlugFromPrevName
      
      onChange({
        ...values,
        name: value,
        ...(shouldUpdateSlug && { slug: newSlug })
      });
      return;
    }
    onChange({
      ...values,
      [name]: type === "checkbox" ? checked : value
    })
  }

  const handleFileChange = (event) => {
    const file = event.target.files && event.target.files[0]
    onChange({
      ...values,
      logo: file || null
    })
  }

  return (
    <form onSubmit={onSubmit}>
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Tên</label>
          <input
            className="form-control"
            name="name"
            value={values.name || ""}
            onChange={handleChange}
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Đường dẫn (slug)</label>
          <input
            className="form-control"
            name="slug"
            value={values.slug || ""}
            onChange={handleChange}
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Logo</label>
          <input
            className="form-control"
            name="logo"
            type="file"
            accept="image/*"
            onChange={handleFileChange}
          />
        </div>
        <div className="col-12">
          <div className="form-check">
            <input
              className="form-check-input"
              type="checkbox"
              name="is_active"
              checked={Boolean(values.is_active)}
              onChange={handleChange}
            />
            <label className="form-check-label">Đang hoạt động</label>
          </div>
        </div>
      </div>

      <div className="d-flex justify-content-end gap-2 mt-4">
        <button type="button" className="btn btn-outline-secondary" onClick={onCancel}>
          Hủy
        </button>
        <button type="submit" className="btn btn-primary">
          Lưu
        </button>
      </div>
    </form>
  )
}

export default BrandForm
